id: I07449797
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T00:10:45+00:00'
last_modified: '2022-06-08T13:19:57.584973+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29664
  title: རྒྱལ་སྲས་ལག་ལེན་སོ་བདུན་མ་དང་དེ་ཡི་མཆན་འགྲེལ་ཡིད་ཀྱི་མུན་སེལ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    BDE8:
      image_group_id: I5551
      title: ''
      total_pages: 75
      order: 1
      base_file: BDE8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
