id: I07449797
legacy_id: P010402
ocr_import_info:
  bdrc_scan_id: W29664
  source: bdrc
  ocr_info:
    timestamp: '2020-03-23T00:10:13'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T14:15:25.495282+00:00'
last_modified: 2022-09-02 22:15:42.340858
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W29664
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW29664
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྒྱལ་སྲས་ལག་ལེན་སོ་བདུན་མ་དང་དེ་ཡི་མཆན་འགྲེལ་ཡིད་ཀྱི་མུན་སེལ།
  author: འབུམ་ཐང་དགེ་བཤེས་ཚུལ་ཁྲིམས་དཔལ་བཟང་།
statistics:
  ocr_word_mean_confidence_index: 0.9697405106782641
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I5551:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5551
      total_pages: 75
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I5551.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9697405106782641
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
