id: P010402
initial_creation_type: ocr
source_metadata:
  id: bdr:W29664
  title: རྒྱལ་སྲས་ལག་ལེན་སོ་བདུན་མ་དང་དེ་ཡི་མཆན་འགྲེལ་ཡིད་ཀྱི་མུན་སེལ
  author: ''
  volumes:
    a4e7992a63e24333a9b2bfa56be953a4:
      image_group_id: I5551
      title: ''
      volume_number: 1
      total_pages: 75
